### PR TITLE
feat(requirements): Support flake8 v5

### LINKED ISSUE #45: Support for flake8==5.x.x
Flake8 5 came out a couple of days ago.
Does anything here need to change other than requirements.txt?

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
Closes #45

### CODE REVIEW

**Comment by jonyscathe** [comment]
I am guessing that this is what is stuffing up those tests: https://github.com/pycqa/flake8/pull/1609

Not sure the best way around that... I don't think it causes any issues, but does mean a few tests aren't quite valid anymore.

Also, given how infrequently this project is updated, perhaps the flake8 upper bound should just be completely removed?

**Comment by mschwager** [comment]
Yes, those `TestFlake8Extension` tests rely a bit on the implementation details of `flake8`. Not ideal, but it was the only way I could test some of the non-standard optimizations done in `dlint`.

The changelog states (https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html):

> Properly differentiate between explicitly ignored / selected and default ignored / selected options (See also [#284](https://github.com/pycqa/flake8/issues/284), [#1576](https://github.com/pycqa/flake8/pull/1576), [#1609](https://github.com/pycqa/flake8/pull/1609)).

Is this just a matter of updating the defaults in `create_options` in `tests/test_extension.py`?

**Comment by jonyscathe** [comment]
@mschwager changing the defaults in `create_options` can almost do it.

Currently the `ignore` and `extend_ignore` tests fail because all linter_classes come up as ignored given that they are not explicitly selected (only implicitly selected with the extended_default_select default of ["DUO"]).
Those two tests can pass if the default value for the "select" kwarg is changed to ["DUO"].
And if that change is made then the only failed test is `test_flake8_extension_get_linter_classes_extended_default_select`

And I'm not sure that the extended_default_select option can be tested using the current test methods. The extended_default_select setting doesn't appear to have any affect on the `engine.decision_for()` value for any given code. If a code (or "DUO" for all DUOXXX codes) is explicitly selected with "select" or "extend_select" and its code is not in the ignore or extend_ignore list then its decision_for() value is `style_guide.Decision.Selected`. If it isn't explicitly selected with "select" or "extend_select" then its decision_for() value will be `style_guide.Decision.Ignored` no matter what the value of extended_default_select is.

I'm not entirely sure how important the extended_default_select test is for dlint. Nor how important the behaviour of get_linter_classes() is with different option args so I'm not sure what the best way forward is for that test.

**Comment by mschwager** [comment]
Thanks for digging into this.

Now I remember where I got the initial `create_options` code: https://github.com/PyCQA/flake8/blob/main/tests/unit/test_decision_engine.py

Copying the latest `create_options` changes from that file to Dlint made the tests pass for me. In other words, `select`, `extend_select`, `ignore`, and `extend_ignore` must default to `None`, not `[]`. If you add those changes to this PR I suspect CI will succeed and we'll be good to go :tada: 

That change shouldn't affect any functionality in Dlint. Since `None` vs. `[]` is an implementation detail of CLI arguments passed to `flake8`, the Dlint optimizations in `get_linter_classes` shouldn't be affected, and it will do the correct thing in `flake8<5.0.0` and `flake8>=5.0.0`.

**Comment by DmytroLitvinov** [comment]
Good morning everyone :wave: 
I have pushed changes. Could some of the maintainers run CI?

**Comment by mschwager** [comment]
It passed! Thanks again for the PR, I will cut a new release of Dlint now :+1:

**Comment by mschwager** [comment]
It's up: https://pypi.org/project/dlint/0.13.0/

**Pull request merged**
